#!/usr/bin/env python3
"""CPU-only, no-training L45 aggregation probe.

It consumes the immutable replay generated by ``audit_l45_aggregation_contract``.
Probe 4 is explicitly GT-privileged and is reported as an oracle diagnostic;
it is never considered a legal output strategy.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path("/data1/LWR/vranlee/SERVER_ONLY/avis/LocateMOT")
sys.path.insert(0, str(ROOT))

from tools.l45_aggregation_common import (
    aggregate_mean,
    aggregate_oracle,
    aggregate_weighted,
    aggregate_zero_mean,
    choose_teacher_threshold,
    fixed_teacher_hard,
    iter_replay,
    metric_summary,
    rank_stats,
)

AUDIT = ROOT / "outputs/l45/audit/aggregation_contract.json"


def sha256(path: Path):
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def bucket(degree):
    if degree < 24:
        return "<24"
    if degree < 32:
        return "24-31"
    if degree < 40:
        return "32-39"
    if degree < 48:
        return "40-47"
    return "48+"


def add_counts(dst, src):
    for key, value in src.items():
        dst[key] = dst.get(key, 0) + int(value)


def distribution(values):
    if not values:
        return {"count": 0, "mean": None, "median": None,
                "q10": None, "q90": None, "max": None}
    x = np.asarray(values, dtype=np.float64)
    return {"count": int(len(x)), "mean": float(x.mean()),
            "median": float(np.median(x)), "q10": float(np.quantile(x, .1)),
            "q90": float(np.quantile(x, .9)), "max": float(x.max())}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--audit", default=str(AUDIT))
    ap.add_argument("--out", default="outputs/l45/eval/aggregation_probe_100.json")
    args = ap.parse_args()
    if Path.cwd().resolve() != ROOT:
        raise RuntimeError(f"wrong cwd: {Path.cwd().resolve()}")
    audit_path = Path(args.audit)
    if not audit_path.is_absolute():
        audit_path = ROOT / audit_path
    audit = json.loads(audit_path.read_text())
    if audit.get("decision") != "enter_untrained_aggregation_probe":
        raise RuntimeError(f"unexpected audit decision: {audit.get('decision')}")
    replay_path = Path(audit["replay_cache"])
    metadata_path = Path(audit["replay_metadata"])
    if sha256(replay_path) != audit["replay_cache_sha256"]:
        raise RuntimeError("replay cache SHA changed after audit")
    metadata = json.loads(metadata_path.read_text())
    with np.load(replay_path, mmap_mode="r", allow_pickle=False) as z:
        arrays = {key: z[key] for key in z.files}
        required = {"teacher", "labels", "objectness", "source", "track_id", "residual"}
        if set(arrays) != required:
            raise RuntimeError(f"replay fields changed: {sorted(arrays)}")
        records = {"calibration": defaultdict(list), "screening": defaultdict(list)}
        rank_total = defaultdict(dict)
        degree_stats = defaultdict(lambda: defaultdict(lambda: {"units": 0, "pairs": 0,
                                                                  "teacher_error": 0,
                                                                  "teacher_correct": 0,
                                                                  "teacher_error_corrections": 0,
                                                                  "teacher_correct_flips": 0}))
        drift_values = defaultdict(list)
        correction_values = defaultdict(list)
        pair_count = 0
        zero_mean_drift = []

        for item, values in iter_replay(arrays, metadata):
            teacher = values["teacher"]
            residual = values["residual"]
            labels = values["label"]
            objectness = values["objectness"]
            mean_score, mean_delta = aggregate_mean(teacher, residual)
            weighted_score, weighted_delta = aggregate_weighted(teacher, residual, tau=.5)
            zero_score, zero_delta, edge_mean = aggregate_zero_mean(teacher, residual, tau=.5)
            oracle_score, oracle_delta = aggregate_oracle(teacher, residual, labels, tau=.5)
            score_map = {
                "teacher": teacher,
                "mean_l43": mean_score,
                "degree_normalized": weighted_score,
                "zero_mean": zero_score,
                "oracle_teacher_error": oracle_score,
            }
            split = str(item["split"])
            base = {"video": str(item["video"]), "expression": str(item["expression"]),
                    "query_index": int(item["query_index"]), "frame": int(item["frame"]),
                    "track_id": values["track_id"], "label": labels,
                    "source": values["source"]}
            for name, score in score_map.items():
                records[split][name].append({**base, "score": score})
            hard = fixed_teacher_hard(labels, objectness, teacher)
            names = ("mean_l43", "degree_normalized", "zero_mean", "oracle_teacher_error")
            degree_key = bucket(len(teacher) - 1)
            for name in names:
                item_rank = rank_stats(teacher, score_map[name], labels, hard)
                add_counts(degree_stats[name][degree_key], item_rank)
                degree_stats[name][degree_key]["units"] += 1
                correction_values[name].append(float(item_rank["teacher_error_corrections"]))
                add_counts(rank_total.setdefault(name, {}), item_rank)
            for name, delta in (("mean_l43", mean_delta), ("degree_normalized", weighted_delta),
                                ("zero_mean", zero_delta), ("oracle_teacher_error", oracle_delta)):
                drift_values[name].append(float(np.mean(delta)))
            zero_mean_drift.append(float(np.mean(zero_delta)))
            pair_count += len(teacher) * max(0, len(teacher) - 1) // 2

        records = {split: dict(value) for split, value in records.items()}
        calibration = choose_teacher_threshold(records["calibration"]["teacher"])
        threshold = float(calibration["threshold"])
        strategies = {}
        for name in records["calibration"]:
            strategies[name] = {
                "calibration_threshold": calibration,
                "calibration": metric_summary(records["calibration"][name], threshold),
                "screening": metric_summary(records["screening"][name], threshold),
            }

    teacher_screen = strategies["teacher"]["screening"]
    legal_names = ("mean_l43", "degree_normalized", "zero_mean")
    deltas = {}
    for name in legal_names:
        current = strategies[name]["screening"]
        deltas[name] = {
            "top1_delta": current["top1_frame_recall"] - teacher_screen["top1_frame_recall"],
            "recall_delta": current["recall"] - teacher_screen["recall"],
            "hard_violation_delta": current["hard_violation_rate"] - teacher_screen["hard_violation_rate"],
            "precision_delta": current["precision"] - teacher_screen["precision"],
            "fp_frame_delta": current["false_positive_candidates_per_frame"] - teacher_screen["false_positive_candidates_per_frame"],
            "multi_positive_recall_delta": current["multi_positive_recall"] - teacher_screen["multi_positive_recall"],
            "empty_rate_delta": current["empty_output_rate"] - teacher_screen["empty_output_rate"],
            "null_false_acceptance_delta": current["null_frame_false_acceptance"] - teacher_screen["null_frame_false_acceptance"],
        }
    def structural_candidate(name):
        d = deltas[name]
        return {
            "top1_preserved": d["top1_delta"] >= -.02,
            "recall_preserved": d["recall_delta"] >= -.03,
            "hard_violation_improved_by_0.05": d["hard_violation_delta"] <= -.05,
            "precision_preserved": d["precision_delta"] >= -.01,
            "fp_frame_preserved": d["fp_frame_delta"] <= .10,
            "multi_positive_preserved": d["multi_positive_recall_delta"] >= -.03,
        }
    candidate_gates = {name: structural_candidate(name) for name in legal_names}
    eligible = [name for name in ("degree_normalized", "zero_mean")
                if all(candidate_gates[name].values())]

    per_degree = {}
    for name, buckets in degree_stats.items():
        if name == "teacher":
            continue
        per_degree[name] = {}
        for key, values in buckets.items():
            per_degree[name][key] = {
                **values,
                "teacher_error_correction_rate": values["teacher_error_corrections"] /
                max(1, values["teacher_error"]),
                "teacher_correct_flip_rate": values["teacher_correct_flips"] /
                max(1, values["teacher_correct"]),
            }

    payload = {
        "format": "locatemot-l45-degree-normalized-pair-aggregation-probe-v1",
        "stage": "L45-B-no-training-aggregation-probe",
        "audit": str(audit_path.resolve()),
        "audit_sha256": sha256(audit_path),
        "replay_cache": str(replay_path.resolve()),
        "replay_cache_sha256": sha256(replay_path),
        "replay_metadata": str(metadata_path.resolve()),
        "manifest_sha256": audit["manifest_sha256"],
        "teacher_checkpoint": audit["teacher_checkpoint"],
        "teacher_checkpoint_sha256": audit["teacher_checkpoint_sha256"],
        "pair_checkpoint": audit["pair_checkpoint"],
        "pair_checkpoint_sha256": audit["pair_checkpoint_sha256"],
        "counts": {
            "screening_units_selected": audit["replay_stats"]["screening_units_selected"],
            "screening_units_available": audit["replay_stats"]["screening_units_available"],
            "calibration_expression_frame_units": len(records["calibration"]["teacher"]),
            "screening_expression_frame_units": len(records["screening"]["teacher"]),
            "screening_candidate_rows": int(strategies["teacher"]["screening"]["candidate_rows"]),
            "positive_negative_unordered_frame_pairs_replayed": int(pair_count),
        },
        "aggregation_contract": {
            "threshold": calibration,
            "probe_2_tau": 0.5,
            "probe_3_tau": 0.5,
            "probe_3_zero_mean": "edge-center then candidate-delta mean-center per frame",
            "probe_4": "GT-privileged teacher-error sign correction; diagnostic only",
            "screening_gt_used_for_threshold": False,
            "screening_gt_used_for_model_selection": False,
            "top_k_or_candidate_filter": False,
            "null_postprocess": False,
        },
        "strategies": strategies,
        "screening_deltas_vs_teacher": deltas,
        "rank_flip_diagnostics": {
            "fixed_teacher_hard_definition": "objectness top-96 then frozen teacher score top-24",
            "by_strategy": {name: dict(values) for name, values in rank_total.items()},
        },
        "per_degree_bucket": per_degree,
        "drift": {name: distribution(values) for name, values in drift_values.items()},
        "zero_mean_frame_drift": distribution(zero_mean_drift),
        "frozen_audit_cancellation": audit["replay_stats"]["residual_cancellation"],
        "candidate_gate_diagnostics": candidate_gates,
        "eligible_for_calibration_head": eligible,
        "decision": "enter_minimal_calibration_head" if eligible else "stop_no_training_probe_failed",
        "oracle_status": "Probe 4 is GT_PRIVILEGED_ORACLE and cannot be selected or emitted",
        "semantic_inputs_excluded": ["source_id", "pool_id", "group_id", "state_key"],
        "token_span_region_alignment": "UNALIGNED; not claimed",
        "motion_language_decomposition": "not claimed; no verified motion-language mask",
    }
    out = Path(args.out)
    if not out.is_absolute():
        out = ROOT / out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2) + "\n")
    print(json.dumps({"out": str(out), "decision": payload["decision"],
                      "deltas": deltas, "candidate_gates": candidate_gates,
                      "screening": {name: strategies[name]["screening"]
                                    for name in strategies}}, indent=2), flush=True)


if __name__ == "__main__":
    main()
